"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, Check, Info, Mic2, Paperclip, Plus, Save, Tag, Users } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { Button } from "@/components/ui/Button";
import { VoiceInputButton } from "@/components/voice/VoiceInputButton";
import { demoEmployees } from "@/data/demo";
import { TASK_PRIORITIES } from "@/lib/constants";
import { taskSchema, type TaskInput } from "@/lib/validators";
import { useAuth } from "@/providers/AuthProvider";
import { createTask } from "@/services/taskService";

export default function NewTaskPage(){ const {employee,demoMode}=useAuth(); const router=useRouter(); const [checklist,setChecklist]=useState<string[]>([]); const [item,setItem]=useState(""); const {register,handleSubmit,setValue,getValues,formState:{errors,isSubmitting,isDirty}}=useForm<TaskInput>({resolver:zodResolver(taskSchema),defaultValues:{title:"",description:"",assigneeId:"",priority:"Medium",dueDate:"",tags:"",requiresApproval:false}});
  const append=(field:"title"|"description",text:string)=>setValue(field,`${getValues(field)}${getValues(field)?" ":""}${text}`,{shouldDirty:true});
  async function submit(values:TaskInput){if(!employee)return;try{const id=demoMode?"task-1":await createTask(values,employee,demoEmployees.find(item=>item.uid===values.assigneeId));toast.success("Task created",{description:"The assignee has been notified."});router.push(`/tasks/${id}`);}catch{toast.error("Task could not be created.");}}
  return <div className="page-wrap"><div className="mb-6 flex items-center gap-3"><Link href="/tasks" className="flex size-10 items-center justify-center rounded-xl border bg-[var(--surface)] text-[var(--muted)] hover:text-[var(--foreground)]"><ArrowLeft className="size-4"/></Link><div><h1 className="page-heading">Create a task</h1><p className="page-subtitle">Give your teammate the context they need to move quickly.</p></div></div>
    <form onSubmit={handleSubmit(submit)} className="grid gap-6 xl:grid-cols-[1fr_340px]"><div className="card p-5 sm:p-7"><div className="space-y-6"><div><div className="flex items-center justify-between"><label className="label" htmlFor="title">Task title <span className="text-red-500">*</span></label><div className="relative"><VoiceInputButton onTranscript={text=>append("title",text)}/></div></div><input id="title" className="control h-12 text-base font-semibold" placeholder="A short, action-oriented title" {...register("title")}/>{errors.title&&<p className="field-error">{errors.title.message}</p>}</div>
      <div><div className="flex items-center justify-between"><label className="label" htmlFor="description">Description <span className="text-red-500">*</span></label><div className="relative"><VoiceInputButton onTranscript={text=>append("description",text)}/></div></div><textarea id="description" className="control min-h-44 resize-y leading-6" placeholder="Explain the outcome, important context, and definition of done…" {...register("description")}/>{errors.description&&<p className="field-error">{errors.description.message}</p>}<p className="mt-2 flex items-center gap-1.5 text-[10px] text-[var(--muted)]"><Mic2 className="size-3"/>Please review names, dates, and technical terms before creating the task.</p></div>
      <div><label className="label">Checklist</label><div className="flex gap-2"><input className="control" value={item} onChange={e=>setItem(e.target.value)} placeholder="Add a step or deliverable" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();if(item.trim()){setChecklist([...checklist,item.trim()]);setItem("")}}}}/><Button type="button" variant="secondary" onClick={()=>{if(item.trim()){setChecklist([...checklist,item.trim()]);setItem("")}}}><Plus className="size-4"/>Add</Button></div>{checklist.length>0&&<div className="mt-3 space-y-2">{checklist.map((value,index)=><div key={`${value}-${index}`} className="flex items-center gap-3 rounded-xl bg-[var(--surface-2)] p-3 text-sm"><span className="flex size-5 items-center justify-center rounded-md border bg-[var(--surface)]"><Check className="size-3 text-[var(--muted)]"/></span><span className="flex-1">{value}</span><button type="button" onClick={()=>setChecklist(checklist.filter((_,i)=>i!==index))} className="text-xs text-red-500">Remove</button></div>)}</div>}</div>
      <div><label className="label" htmlFor="tags">Tags</label><div className="relative"><Tag className="absolute left-3 top-3.5 size-4 text-[var(--muted)]"/><input id="tags" className="control pl-10" placeholder="campaign, client, follow-up" {...register("tags")}/></div><p className="mt-1.5 text-[10px] text-[var(--muted)]">Separate tags with commas.</p></div>
      <div><label className="label">Attachments</label><label className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed bg-[var(--surface-2)] p-5 text-center hover:border-cyan-400"><Paperclip className="mb-2 size-5 text-[#0796c2]"/><span className="text-xs font-bold">Drop files here or choose files</span><span className="mt-1 text-[10px] text-[var(--muted)]">PDF, Office files, images or text · up to 10 MB</span><input type="file" multiple className="sr-only" onChange={()=>toast.info("Files will upload after the task is created.")}/></label></div></div></div>
    <aside className="space-y-5"><div className="card p-5"><h2 className="mb-5 text-sm font-extrabold">Assignment</h2><div className="space-y-5"><div><label className="label" htmlFor="assignee">Assignee <span className="text-red-500">*</span></label><div className="relative"><Users className="absolute left-3 top-3.5 size-4 text-[var(--muted)]"/><select id="assignee" className="control pl-10" {...register("assigneeId")}><option value="">Choose a teammate</option>{demoEmployees.map(item=><option key={item.uid} value={item.uid}>{item.fullName} · {item.departmentName}</option>)}</select></div>{errors.assigneeId&&<p className="field-error">{errors.assigneeId.message}</p>}</div><div><label className="label" htmlFor="priority">Priority</label><select id="priority" className="control" {...register("priority")}>{TASK_PRIORITIES.map(value=><option key={value}>{value}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><label className="label" htmlFor="startDate">Start</label><input id="startDate" type="date" className="control px-2 text-xs" {...register("startDate")}/></div><div><label className="label" htmlFor="dueDate">Due <span className="text-red-500">*</span></label><input id="dueDate" type="date" className="control px-2 text-xs" {...register("dueDate")}/></div></div>{errors.dueDate&&<p className="field-error">{errors.dueDate.message}</p>}<div><label className="label" htmlFor="project">Project</label><input id="project" className="control" placeholder="Select or type project" {...register("projectName")}/></div><label className="flex items-start gap-3 rounded-xl bg-[var(--surface-2)] p-3"><input type="checkbox" className="mt-0.5 size-4 accent-[#0796c2]" {...register("requiresApproval")}/><span><span className="block text-xs font-bold">Requires approval</span><span className="mt-1 block text-[10px] leading-4 text-[var(--muted)]">A reviewer must approve this task before completion.</span></span></label></div></div>
      <div className="rounded-xl border border-cyan-200 bg-[var(--cyan-soft)] p-4 text-xs leading-5 text-cyan-900 dark:border-cyan-900 dark:text-cyan-200"><Info className="mr-2 inline size-4"/>The assignee will receive an in-app notification after creation.</div><div className="flex gap-2"><Button type="button" variant="secondary" className="flex-1" onClick={()=>toast.success("Draft saved locally")}><Save className="size-4"/>Draft</Button><Button type="submit" className="flex-[1.4]" loading={isSubmitting}>Create task</Button></div>{isDirty&&<p className="text-center text-[10px] text-[var(--muted)]">You have unsaved changes.</p>}</aside></form>
  </div>;
}
