"use client";

import { ArrowLeft, CalendarDays, Check, CheckCircle2, CircleDot, Download, Ellipsis, FileText, MessageSquare, Paperclip, Play, Send, ShieldCheck, UserRound } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";
import { toast } from "sonner";
import { Avatar } from "@/components/ui/Avatar";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Skeleton } from "@/components/ui/Skeleton";
import { PriorityBadge, StatusBadge } from "@/components/tasks/TaskBadges";
import { VoiceInputButton } from "@/components/voice/VoiceInputButton";
import { demoTasks } from "@/data/demo";
import { isValidTransition } from "@/lib/permissions";
import { useAuth } from "@/providers/AuthProvider";
import { getTask, updateTaskStatus } from "@/services/taskService";
import type { TaskStatus } from "@/types";

const activity=[{text:"moved the task to In Progress",by:"Aarav Mehta",time:"Today, 10:42 AM"},{text:"added Nisha as an assignee",by:"Aarav Mehta",time:"Yesterday, 4:18 PM"},{text:"created this task",by:"Aarav Mehta",time:"15 Jul, 9:30 AM"}];
const initialComments=[{id:"1",name:"Nisha Patel",time:"Today, 11:04 AM",text:"I’ve completed the first creative pass. The mobile formats still need a final export."},{id:"2",name:"Aarav Mehta",time:"Today, 11:22 AM",text:"Looks good. Please include the updated CTA from the client notes before submitting."}];
export default function TaskDetailPage(){ const {id}=useParams<{id:string}>(); const {employee,demoMode}=useAuth(); const {data:task,isLoading}=useQuery({queryKey:["task",id,demoMode],queryFn:()=>demoMode?demoTasks.find(item=>item.id===id)||demoTasks[0]:getTask(id)}); const [comment,setComment]=useState(""); const [comments,setComments]=useState(initialComments); const [localStatus,setLocalStatus]=useState<TaskStatus|undefined>(); const currentStatus=localStatus||task?.status;
  const actions=useMemo(()=>{if(!task||!currentStatus)return[]; const candidates: {status:TaskStatus;label:string;icon:typeof Play}[]=[{status:"Accepted",label:"Accept task",icon:Check},{status:"In Progress",label:"Start work",icon:Play},{status:"Submitted for Review",label:"Submit for review",icon:Send},{status:"Completed",label:task.requiresApproval?"Approve & complete":"Complete task",icon:CheckCircle2}];return candidates.filter(item=>isValidTransition(currentStatus,item.status,task.requiresApproval));},[task,currentStatus]);
  async function changeStatus(next:TaskStatus){if(!task)return;try{if(!demoMode)await updateTaskStatus({...task,status:currentStatus!},next);setLocalStatus(next);toast.success(`Task moved to ${next}`);}catch(error){toast.error(error instanceof Error?error.message:"Status could not be changed.");}}
  function postComment(){if(!comment.trim())return;setComments([...comments,{id:String(Date.now()),name:employee?.fullName||"You",time:"Just now",text:comment.trim()}]);setComment("");toast.success("Comment added");}
  if(isLoading)return <div className="page-wrap space-y-4"><Skeleton className="h-10 w-72"/><Skeleton className="h-52"/><Skeleton className="h-96"/></div>;
  if(!task)return <div className="page-wrap"><div className="card p-10 text-center"><h1 className="text-xl font-bold">Task not found</h1><Link href="/tasks" className="mt-4 inline-block text-sm font-bold text-[#0796c2]">Return to tasks</Link></div></div>;
  return <div className="page-wrap"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Link href="/tasks" className="flex items-center gap-2 text-xs font-bold text-[var(--muted)] hover:text-[var(--foreground)]"><ArrowLeft className="size-4"/>Back to tasks</Link><Button variant="secondary" size="icon" aria-label="More actions"><Ellipsis className="size-5"/></Button></div>
    <header className="card mb-6 p-5 sm:p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div className="min-w-0"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="text-xs font-extrabold tracking-wide text-[var(--muted)]">{task.taskNumber}</span><StatusBadge status={currentStatus!}/><PriorityBadge priority={task.priority}/></div><h1 className="text-2xl font-extrabold tracking-[-.035em] sm:text-3xl">{task.title}</h1><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[var(--muted)]"><span className="flex items-center gap-1.5"><UserRound className="size-3.5"/>Created by <strong className="text-[var(--foreground)]">{task.createdByName}</strong></span><span className="flex items-center gap-1.5"><CalendarDays className="size-3.5"/>Due <strong className="text-[var(--foreground)]">{format(new Date(task.dueDate),"d MMMM yyyy")}</strong></span>{task.projectName&&<span className="flex items-center gap-1.5"><CircleDot className="size-3.5"/>{task.projectName}</span>}</div></div><div className="flex flex-wrap gap-2">{actions.map(({status,label,icon:Icon},index)=><Button key={status} variant={index===0?"primary":"secondary"} onClick={()=>changeStatus(status)}><Icon className="size-4"/>{label}</Button>)}</div></div></header>
    <div className="grid gap-6 xl:grid-cols-[1fr_320px]"><main className="space-y-6"><section className="card p-5 sm:p-7"><h2 className="mb-4 text-sm font-extrabold">Description</h2><p className="whitespace-pre-line text-sm leading-7 text-[var(--muted)]">{task.description}</p>{task.blockedReason&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 dark:border-red-900 dark:bg-red-950/20"><div className="text-xs font-extrabold text-red-700 dark:text-red-300">Blocked reason</div><p className="mt-1 text-xs text-red-600 dark:text-red-400">{task.blockedReason}</p></div>}
      {task.tags.length>0&&<div className="mt-5 flex flex-wrap gap-2">{task.tags.map(tag=><Badge key={tag}>#{tag}</Badge>)}</div>}</section>
      <section className="card p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-sm font-extrabold">Checklist</h2><p className="mt-1 text-[11px] text-[var(--muted)]">2 of 3 items completed</p></div><span className="text-xs font-bold text-[#0796c2]">67%</span></div><div className="mb-5 h-2 overflow-hidden rounded-full bg-[var(--surface-2)]"><div className="h-full w-2/3 rounded-full bg-[#17a9d6]"/></div><div className="space-y-2">{["Confirm availability with site coordinators","Share the draft schedule with sales leads","Publish the final calendar"].map((item,index)=><label key={item} className="flex cursor-pointer items-center gap-3 rounded-xl border p-3.5 hover:bg-[var(--surface-2)]"><input type="checkbox" defaultChecked={index<2} className="size-4 accent-[#0796c2]"/><span className={`text-xs ${index<2?"text-[var(--muted)] line-through":"font-semibold"}`}>{item}</span></label>)}</div></section>
      <section className="card p-5 sm:p-7"><div className="mb-5 flex items-center gap-2"><MessageSquare className="size-4 text-[#0796c2]"/><h2 className="text-sm font-extrabold">Discussion <span className="ml-1 text-[var(--muted)]">{comments.length}</span></h2></div><div className="space-y-5">{comments.map(item=><article key={item.id} className="flex gap-3"><Avatar name={item.name}/><div className="min-w-0 flex-1 rounded-xl bg-[var(--surface-2)] p-4"><div className="mb-2 flex items-center justify-between gap-3"><span className="text-xs font-bold">{item.name}</span><span className="text-[10px] text-[var(--muted)]">{item.time}</span></div><p className="text-xs leading-5 text-[var(--muted)]">{item.text}</p></div></article>)}</div><div className="mt-6 flex gap-3 border-t pt-5"><Avatar name={employee?.fullName||"You"}/><div className="relative flex-1"><textarea className="control min-h-24 resize-none pr-12" placeholder="Write a comment or @mention a teammate…" value={comment} onChange={e=>setComment(e.target.value)}/><div className="absolute bottom-2 right-2"><VoiceInputButton compact onTranscript={text=>setComment(value=>`${value}${value?" ":""}${text}`)}/></div><div className="mt-2 flex justify-between"><Button variant="ghost" size="sm"><Paperclip className="size-3.5"/>Attach</Button><Button size="sm" onClick={postComment}><Send className="size-3.5"/>Comment</Button></div></div></div></section></main>
      <aside className="space-y-5"><section className="card p-5"><h2 className="mb-5 text-sm font-extrabold">Task details</h2><dl className="space-y-5"><div><dt className="mb-2 text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Assignee</dt><dd className="flex items-center gap-3"><Avatar name={task.assignedToDetails?.[0]?.name||"Assigned"}/><div><div className="text-xs font-bold">{task.assignedToDetails?.[0]?.name||"Assigned employee"}</div><div className="text-[10px] text-[var(--muted)]">Primary assignee</div></div></dd></div><div className="grid grid-cols-2 gap-4"><div><dt className="mb-1 text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Priority</dt><dd><PriorityBadge priority={task.priority}/></dd></div><div><dt className="mb-1 text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Status</dt><dd><StatusBadge status={currentStatus!}/></dd></div></div><div><dt className="mb-2 text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Progress</dt><dd><div className="flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-[var(--surface-2)]"><div className="h-full rounded-full bg-[#17a9d6]" style={{width:`${task.progressPercentage}%`}}/></div><span className="text-xs font-bold">{task.progressPercentage}%</span></div></dd></div><div className="grid grid-cols-2 gap-4"><div><dt className="mb-1 text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Created</dt><dd className="text-xs font-semibold">{format(new Date(task.createdAt),"d MMM yyyy")}</dd></div><div><dt className="mb-1 text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Due</dt><dd className="text-xs font-semibold">{format(new Date(task.dueDate),"d MMM yyyy")}</dd></div></div>{task.requiresApproval&&<div className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-xs font-semibold text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300"><ShieldCheck className="size-4"/>Approval required</div>}</dl></section>
      <section className="card p-5"><h2 className="mb-4 text-sm font-extrabold">Attachments</h2><div className="rounded-xl border p-3"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-red-50 text-red-600"><FileText className="size-4"/></span><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">site-schedule-draft.pdf</div><div className="text-[10px] text-[var(--muted)]">1.8 MB</div></div><button aria-label="Download attachment" className="text-[var(--muted)]"><Download className="size-4"/></button></div></div><Button variant="ghost" size="sm" className="mt-2 w-full"><Paperclip className="size-3.5"/>Add attachment</Button></section>
      <section className="card p-5"><h2 className="mb-4 text-sm font-extrabold">Activity</h2><div className="space-y-4">{activity.map((item,index)=><div key={item.time} className="relative flex gap-3"><span className="relative z-10 mt-1 size-2.5 rounded-full border-2 border-[#17a9d6] bg-[var(--surface)]"/>{index<activity.length-1&&<span className="absolute left-[4px] top-3 h-[calc(100%+8px)] w-px bg-[var(--border)]"/>}<div><p className="text-[11px] leading-4"><strong>{item.by}</strong> <span className="text-[var(--muted)]">{item.text}</span></p><p className="mt-1 text-[9px] text-[var(--muted)]">{item.time}</p></div></div>)}</div></section></aside>
    </div>
  </div>;
}
