"use client";

import { CalendarClock, CheckCheck, ChevronRight, CircleAlert, Clock3, Megaphone, Sparkles, Users2 } from "lucide-react";
import Link from "next/link";
import { format } from "date-fns";
import { MetricCard } from "@/components/dashboard/MetricCard";
import { WorkloadChart } from "@/components/dashboard/WorkloadChart";
import { TaskCard } from "@/components/tasks/TaskCard";
import { Avatar } from "@/components/ui/Avatar";
import { Badge } from "@/components/ui/Badge";
import { Skeleton } from "@/components/ui/Skeleton";
import { demoAnnouncements, demoEmployees } from "@/data/demo";
import { useTasks } from "@/hooks/useTasks";
import { useAuth } from "@/providers/AuthProvider";

export default function DashboardPage() {
  const { employee } = useAuth(); const { data: tasks = [], isLoading } = useTasks(); const first = employee?.fullName.split(" ")[0] || "there";
  const metrics = { assigned: tasks.filter(t=>t.status!=="Completed"&&t.status!=="Cancelled").length, dueToday: tasks.filter(t=>new Date(t.dueDate).toDateString()===new Date().toDateString()).length, overdue: tasks.filter(t=>new Date(t.dueDate)<new Date()&&t.status!=="Completed").length, review: tasks.filter(t=>t.status==="Submitted for Review").length };
  return <div className="page-wrap">
    <section className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-[#0796c2]"><Sparkles className="size-3.5" />{format(new Date(),"EEEE, d MMMM")}</div><h1 className="page-heading">Good morning, {first}</h1><p className="page-subtitle">Here’s what needs your attention across the team today.</p></div><div className="flex items-center gap-2 text-xs text-[var(--muted)]"><span className="size-2 rounded-full bg-emerald-500" />Workspace is up to date</div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Active assignments" value={metrics.assigned} detail="Across your current workspace" icon={CalendarClock} trend="up"/><MetricCard label="Due today" value={metrics.dueToday} detail="Plan time before close of day" icon={Clock3} tone="purple"/><MetricCard label="Overdue" value={metrics.overdue} detail="Needs action or a new due date" icon={CircleAlert} tone="red"/><MetricCard label="Awaiting review" value={metrics.review} detail="Ready for manager feedback" icon={CheckCheck} tone="green"/></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.5fr_.8fr]"><div className="card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-base font-extrabold tracking-tight">Priority work</h2><p className="mt-1 text-xs text-[var(--muted)]">Tasks closest to their deadline</p></div><Link href="/tasks" className="flex items-center gap-1 text-xs font-bold text-[#0796c2]">View all <ChevronRight className="size-4" /></Link></div>{isLoading?<div className="grid gap-3 md:grid-cols-2"><Skeleton className="h-48"/><Skeleton className="h-48"/></div>:<div className="grid gap-3 md:grid-cols-2">{tasks.slice(0,4).map(task=><TaskCard key={task.id} task={task} compact/>)}</div>}</div>
      <div className="card overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4"><div className="flex items-center gap-2"><Megaphone className="size-4 text-[#0796c2]"/><h2 className="text-sm font-extrabold">Announcements</h2></div><Link href="/announcements" className="text-[11px] font-bold text-[#0796c2]">See all</Link></div><div className="divide-y">{demoAnnouncements.map(item=><article key={item.id} className="p-5"><div className="mb-2 flex items-center gap-2">{item.isPinned&&<Badge tone="cyan">Pinned</Badge>}<span className="text-[10px] text-[var(--muted)]">{format(new Date(item.createdAt),"d MMM")}</span></div><h3 className="text-sm font-bold">{item.title}</h3><p className="mt-1.5 line-clamp-2 text-xs leading-5 text-[var(--muted)]">{item.content}</p></article>)}</div></div>
    </section>
    {employee?.role!=="employee"&&<section className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_.8fr]"><div className="card p-5 sm:p-6"><div className="mb-2 flex items-center justify-between"><div><h2 className="text-base font-extrabold tracking-tight">Team workload</h2><p className="mt-1 text-xs text-[var(--muted)]">Active and review-stage tasks by team member</p></div><div className="flex gap-3 text-[10px] font-semibold text-[var(--muted)]"><span className="flex items-center gap-1"><i className="size-2 rounded-full bg-[#17a9d6]"/>Active</span><span className="flex items-center gap-1"><i className="size-2 rounded-full bg-amber-500"/>Review</span></div></div><WorkloadChart/></div><div className="card p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><Users2 className="size-4 text-[#0796c2]"/><h2 className="text-sm font-extrabold">Team availability</h2></div><Link href="/employees" className="text-[11px] font-bold text-[#0796c2]">Directory</Link></div><div className="space-y-4">{demoEmployees.slice(1,6).map(person=><div key={person.uid} className="flex items-center gap-3"><Avatar name={person.fullName}/><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">{person.fullName}</div><div className="truncate text-[10px] text-[var(--muted)]">{person.designation}</div></div><span className="flex items-center gap-1.5 text-[10px] text-[var(--muted)]"><i className={`size-2 rounded-full ${person.availabilityStatus==="Available"?"bg-emerald-500":person.availabilityStatus==="On Leave"?"bg-slate-400":"bg-amber-500"}`}/>{person.availabilityStatus}</span></div>)}</div></div></section>}
  </div>;
}
